
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import org.mindrot.jbcrypt.BCrypt;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Legion
 */
public class Giris extends javax.swing.JFrame {

    VeriTabani db = new VeriTabani();

    /**
     * Creates new form Giris
     */
    public Giris() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(signIn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        nicknameEmail = new javax.swing.JTextField();
        signIn = new javax.swing.JButton();
        signUp = new javax.swing.JButton();
        iconUser = new javax.swing.JLabel();
        iconPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setResizable(false);
        setSize(new java.awt.Dimension(350, 450));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));

        password.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("passwordfield");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        nicknameEmail.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        nicknameEmail.setForeground(new java.awt.Color(153, 153, 153));
        nicknameEmail.setText("Nickname or E-mail");
        nicknameEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nicknameEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicknameEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicknameEmailFocusLost(evt);
            }
        });

        signIn.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        signIn.setText("Sign In");
        signIn.setAutoscrolls(true);
        signIn.setContentAreaFilled(false);
        signIn.setFocusPainted(false);
        signIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        signUp.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        signUp.setText("Sign Up");
        signUp.setContentAreaFilled(false);
        signUp.setFocusPainted(false);
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N

        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/padlock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(iconUser)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nicknameEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(iconPassword)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(signIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(signUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nicknameEmail))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(iconPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(password))
                                .addGap(15, 15, 15)
                                .addComponent(signIn)
                                .addGap(34, 34, 34)
                                .addComponent(signUp)
                                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void nicknameEmailFocusGained(java.awt.event.FocusEvent evt) {
        if(nicknameEmail.getText().equals("Nickname or E-mail")){
            nicknameEmail.setText("");
            nicknameEmail.setForeground(Color.black);
        }
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconUser.setBorder(border);
    }

    private void nicknameEmailFocusLost(java.awt.event.FocusEvent evt) {
        if(nicknameEmail.getText().equals("Nickname or E-mail") || nicknameEmail.getText().trim().equals("")){
            nicknameEmail.setText("Nickname or E-mail");
            nicknameEmail.setForeground(new Color(153,153,153));
        }
        iconUser.setBorder(null);
    }

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {
        if(String.valueOf(password.getPassword()).equals("passwordfield")){
            password.setText("");
            password.setForeground(Color.black);
        }
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconPassword.setBorder(border);
    }

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {
        if(String.valueOf(password.getPassword()).equals("passwordfield") || String.valueOf(password.getPassword()).trim().equals("") ){
            password.setText("passwordfield");
            password.setForeground(new Color(153,153,153));
        }
        iconPassword.setBorder(null);
    }

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {
        String nicknameEmailS = nicknameEmail.getText();
        String passwordS = String.valueOf(password.getPassword());
        Member member = db.getMember(nicknameEmailS);

        if(nicknameEmailS.trim().equals("") || nicknameEmailS.trim().equals("Nickname or E-mail")){
            JOptionPane.showMessageDialog(null, "Nickname/E-mail cannot be left blank.", "Blank Nickname/Email Error!",2);
        }else if(passwordS.trim().equals("") || passwordS.trim().equals("passwordfield")){
            JOptionPane.showMessageDialog(null, "Password cannot be left blank.", "Blank Password Error!",2);
        }else{
            if(member != null){
                if(BCrypt.checkpw(passwordS, member.getPassword())){
                    JOptionPane.showMessageDialog(null, "Login Successful");
                }else{
                    JOptionPane.showMessageDialog(null, "The password is incorrect.", "Password Error!",2);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "There is no such user.", "User Not Found Error!",2);
            }
        }
    }

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {
        Kayit k = new Kayit();
        setVisible(false);
        k.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nicknameEmail;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signIn;
    private javax.swing.JButton signUp;
    // End of variables declaration
}
